export {
  buildCatalogueHref,
  calculateDiscountPercentage,
  catalogueColours,
  catalogueMaterials,
  catalogueSellerLocations,
  catalogueSortOptions,
  createCatalogueResult,
  findCategoryBySlug,
  findProductBySlug,
  formatPrice,
  listCatalogueProducts,
  listRelatedProducts,
  parseCatalogueFilters,
} from './catalogue.service';
